version: "3.4"

services: 
    proxy:
        build: 
            context: ./Proxy
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
    
    client:
        depends_on:
            - api
        build:
            context: ./Client
            dockerfile: TemplateS.Client/TemplateS.Client/Dockerfile
        ports: 
            - "4200:80"
    
    api:
        depends_on:
            - sqldata
        build: 
            context: ./API
            dockerfile: TemplateS.API/Dockerfile
        ports: 
            - "5000:80"
        environment:
            DBConnection: "Data Source=sqldata,1433;Initial Catalog=master;Persist Security Info=True;User ID=sa;Password=Stefanini@123"

    sqldata:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - SA_PASSWORD=Stefanini@123
            - ACCEPT_EULA=Y
        ports:
            - "5434:1433"