version: "3.4"

services: 
    #proxy:
    #    build: 
    #        context: "./Proxy"
    #        dockerfile: "Dockerfile"
    #    ports: 
    #        - "80:80"
    #    restart: always

    #clientangular:
    #    depends_on:
    #        - api
    #    build:
    #        context: "./Client/TemplateS.Client/TemplateS.Client"
    #        dockerfile: "Dockerfile"
    #    ports: 
    #        - "4200:4200"
    #    expose:
    #        - "4200"

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
    
    sqldata:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        container_name: sqldata
        environment:
            MSSQL_SA_PASSWORD: "Desafio123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
        ports: 
            - "1433:1433"

    api:
        depends_on:
            - sqldata
            - rabbitmq
        container_name: api
        build: 
            context: "./API/TemplateS.API"
            dockerfile: "Dockerfile"
        ports: 
            - "5000:80"

    clientreact:
        depends_on:
            - api
        container_name: clientreact
        build:
            context: "./Client/TemplateS.Client/TemplateS.Client.React"
            dockerfile: "Dockerfile"
        ports: 
            - "3000:80"